apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secrets.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: sentinel-hub-api
  app.kubernetes.io/part-of: sentinel

images:
- name: sentinel-hub-api
  newTag: latest
